// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasswordManager.TelegramClient.Data;

#nullable disable

namespace PasswordManager.TelegramClient.Migrations
{
    [DbContext(typeof(TelegramClientContext))]
    [Migration("20240513184315_Add request forms")]
    partial class Addrequestforms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasswordManager.TelegramClient.Data.Entities.TelegramUserDataEntity", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramUserId"));

                    b.Property<Guid?>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Locale")
                        .HasColumnType("integer");

                    b.Property<string>("MasterPasswordHash")
                        .HasColumnType("text");

                    b.HasKey("TelegramUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PasswordManager.TelegramClient.Data.Entities.TelegramUserRequestFormEntity", b =>
                {
                    b.Property<Guid>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("FormId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("PasswordManager.TelegramClient.Data.Entities.TelegramUserRequestFormEntity", b =>
                {
                    b.HasOne("PasswordManager.TelegramClient.Data.Entities.TelegramUserDataEntity", "User")
                        .WithOne("RequestForm")
                        .HasForeignKey("PasswordManager.TelegramClient.Data.Entities.TelegramUserRequestFormEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasswordManager.TelegramClient.Data.Entities.TelegramUserDataEntity", b =>
                {
                    b.Navigation("RequestForm");
                });
#pragma warning restore 612, 618
        }
    }
}
