//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.TelegramClient.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBodies {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBodies() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PasswordManager.TelegramClient.Resources.MessageBodies", typeof(MessageBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WrongMessageWarningBody {
            get {
                return ResourceManager.GetString("WrongMessageWarningBody", resourceCulture);
            }
        }
        
        internal static string SetUpMasterPasswordMessageBody {
            get {
                return ResourceManager.GetString("SetUpMasterPasswordMessageBody", resourceCulture);
            }
        }
        
        internal static string YouNeedAtLeastOneCharForPassword {
            get {
                return ResourceManager.GetString("YouNeedAtLeastOneCharForPassword", resourceCulture);
            }
        }
        
        internal static string YourMasterPasswordIsApplied {
            get {
                return ResourceManager.GetString("YourMasterPasswordIsApplied", resourceCulture);
            }
        }
        
        internal static string YouHaveNoAccounts {
            get {
                return ResourceManager.GetString("YouHaveNoAccounts", resourceCulture);
            }
        }
        
        internal static string AccountsList {
            get {
                return ResourceManager.GetString("AccountsList", resourceCulture);
            }
        }
        
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        internal static string SendUrlToAddAccount {
            get {
                return ResourceManager.GetString("SendUrlToAddAccount", resourceCulture);
            }
        }
        
        internal static string SendWebsiteNicknameToAddAccount {
            get {
                return ResourceManager.GetString("SendWebsiteNicknameToAddAccount", resourceCulture);
            }
        }
        
        internal static string SendUserToAddAccount {
            get {
                return ResourceManager.GetString("SendUserToAddAccount", resourceCulture);
            }
        }
        
        internal static string SendPasswordToAddAccount {
            get {
                return ResourceManager.GetString("SendPasswordToAddAccount", resourceCulture);
            }
        }
        
        internal static string AddAccountFinalStep {
            get {
                return ResourceManager.GetString("AddAccountFinalStep", resourceCulture);
            }
        }
        
        internal static string WrongUrlFormat {
            get {
                return ResourceManager.GetString("WrongUrlFormat", resourceCulture);
            }
        }
        
        internal static string WrongMasterPassword {
            get {
                return ResourceManager.GetString("WrongMasterPassword", resourceCulture);
            }
        }
        
        internal static string AddAccountSuccess {
            get {
                return ResourceManager.GetString("AddAccountSuccess", resourceCulture);
            }
        }
        
        internal static string SendMasterPasswordToEncrypt {
            get {
                return ResourceManager.GetString("SendMasterPasswordToEncrypt", resourceCulture);
            }
        }
        
        internal static string GetCredentialsProvideMasterPassword {
            get {
                return ResourceManager.GetString("GetCredentialsProvideMasterPassword", resourceCulture);
            }
        }
        
        internal static string HereIsYourPassword {
            get {
                return ResourceManager.GetString("HereIsYourPassword", resourceCulture);
            }
        }
        
        internal static string ChooseAccountForCredentials {
            get {
                return ResourceManager.GetString("ChooseAccountForCredentials", resourceCulture);
            }
        }
        
        internal static string DeleteAccountConfirmation {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmation", resourceCulture);
            }
        }
        
        internal static string WrongDeleteAccountConfirmation {
            get {
                return ResourceManager.GetString("WrongDeleteAccountConfirmation", resourceCulture);
            }
        }
        
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        internal static string ChangeMasterPasswordConditions {
            get {
                return ResourceManager.GetString("ChangeMasterPasswordConditions", resourceCulture);
            }
        }
        
        internal static string WrongLinesCount {
            get {
                return ResourceManager.GetString("WrongLinesCount", resourceCulture);
            }
        }
        
        internal static string NewMasterPasswordNotMatch {
            get {
                return ResourceManager.GetString("NewMasterPasswordNotMatch", resourceCulture);
            }
        }
        
        internal static string MasterPasswordChanged {
            get {
                return ResourceManager.GetString("MasterPasswordChanged", resourceCulture);
            }
        }
    }
}
