//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.TelegramClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.TelegramClient.Resources.MessageBodies", typeof(MessageBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your accounts:
        ///{0}.
        /// </summary>
        internal static string AccountsList {
            get {
                return ResourceManager.GetString("AccountsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error. Please contact a developer..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send URL of your website:.
        /// </summary>
        internal static string SendUrlToAddAccount {
            get {
                return ResourceManager.GetString("SendUrlToAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a nickname for yout website:.
        /// </summary>
        internal static string SendWebsiteNicknameToAddAccount {
            get {
                return ResourceManager.GetString("SendWebsiteNicknameToAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a master password:.
        /// </summary>
        internal static string SetUpMasterPasswordMessageBody {
            get {
                return ResourceManager.GetString("SetUpMasterPasswordMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option you want to do..
        /// </summary>
        internal static string WrongMessageWarningBody {
            get {
                return ResourceManager.GetString("WrongMessageWarningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts list is empty..
        /// </summary>
        internal static string YouHaveNoAccounts {
            get {
                return ResourceManager.GetString("YouHaveNoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to type at least a single character for your master password..
        /// </summary>
        internal static string YouNeedAtLeastOneCharForPassword {
            get {
                return ResourceManager.GetString("YouNeedAtLeastOneCharForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your master password is successfully applied!.
        /// </summary>
        internal static string YourMasterPasswordIsApplied {
            get {
                return ResourceManager.GetString("YourMasterPasswordIsApplied", resourceCulture);
            }
        }
    }
}
