name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Build the Docker image PasswordStorageService
      run: docker build . --file PasswordStorageService/PasswordStorageService.Dockerfile --tag soteyl/password_manager:storage_service
      
    - name: Push the Docker image PasswordStorageService
      run: docker push soteyl/password_manager:storage_service

    - name: Build the Docker image
      run: docker build . --file PasswordManager.TelegramClient/TelegramClient.Dockerfile --tag soteyl/password_manager:telegram_client
      
    - name: Push the Docker image
      run: docker push soteyl/password_manager:telegram_client
